### ISSUE TITLE
Additional Filtering of Block

### ISSUE THREAD

**Issue by LMT337** [LMT337/qc_metrics.pl#1]
Script currently filters block between ---/--- and extracts requested key value pairs to return in column with keys as column header. Within the --- block, additional sections need to be filtered to be returned in this same format. Sections will have be indicated by a key, these sections are repetitive with each other they will need a $hash{block}{key} = value, data construction so as not to overwrite duplicate key names and maintain identity with block name and identify the block in the returned column header.

---
field
field
field
ALL: **BLOCK ID**
  "#READS": 37503408 **BLOCK START**
  "#SEQ_ID": A-LOAD-LD010714-CL-NCR-08AD10087
  "#SNPS": 1827522
  AVG_DP: 20.52
  CHIPLK0: NA
  CHIPLK1: NA
  CHIPMIX: NA
  CHIP_ID: NA
  CHIP_RA: NA
  CHIP_RH: NA
  DPREF: NA
  FREELK0: 8707287.18
  FREELK1: 8157472.87
  FREEMIX: 0.03246
  FREE_RA: NA
  FREE_RH: NA
  RDPALT: NA
  RDPHET: NA
  RG: ALL **BLOCK END**
field
field
FIRST_OF_PAIR:  **BLOCK ID**
  BAD_CYCLES: 0 **BLOCK START**
  CATEGORY: FIRST_OF_PAIR
  LIBRARY: ''
  MEAN_READ_LENGTH: 151
  PCT_ADAPTER: 0.011839
  PCT_CHIMERAS: 0.001998
  PCT_PF_READS: 1
  PCT_PF_READS_ALIGNED: 0.982232
  PCT_READS_ALIGNED_IN_PAIRS: 0.997606
  PF_ALIGNED_BASES: 44081985030
  PF_HQ_ALIGNED_BASES: 41936720545
  PF_HQ_ALIGNED_Q20_BASES: 40859213537
  PF_HQ_ALIGNED_READS: 283123393
  PF_HQ_ERROR_RATE: 0.005756
  PF_HQ_MEDIAN_MISMATCHES: 0
  PF_INDEL_RATE: 0.000269
  PF_MISMATCH_RATE: 0.007133
  PF_NOISE_READS: 0
  PF_READS: 305314189
  PF_READS_ALIGNED: 299889344
  READS_ALIGNED_IN_PAIRS: 299171536
  READ_GROUP: ''
  SAMPLE: ''
  STRAND_BALANCE: 0.500053
  TOTAL_READS: 305314189 **BLOCK END**
field 
field
PAIR:  **BLOCK ID**
  BAD_CYCLES: 0 **BLOCK START**
  CATEGORY: PAIR
  LIBRARY: ''
  MEAN_READ_LENGTH: 151
  PCT_ADAPTER: 0.011815
  PCT_CHIMERAS: 0.001998
  PCT_PF_READS: 1
  PCT_PF_READS_ALIGNED: 0.981218
  PCT_READS_ALIGNED_IN_PAIRS: 0.998637
  PF_ALIGNED_BASES: 87548587953
  PF_HQ_ALIGNED_BASES: 83303960988
  PF_HQ_ALIGNED_Q20_BASES: 79759839089
  PF_HQ_ALIGNED_READS: 565260056
  PF_HQ_ERROR_RATE: 0.007811
  PF_HQ_MEDIAN_MISMATCHES: 0
  PF_INDEL_RATE: 0.000264
  PF_MISMATCH_RATE: 0.009144
  PF_NOISE_READS: 0
  PF_READS: 610628378
  PF_READS_ALIGNED: 599159445
  READS_ALIGNED_IN_PAIRS: 598343072
  READ_GROUP: ''
  SAMPLE: ''
  STRAND_BALANCE: 0.499755
  TOTAL_READS: 610628378 **BLOCK END**
field
field

---

**Comment by ahwagner** [comment]
After reviewing the code, it seems like you have most of what you need here already. I have noticed that a recurring error is the lack of the following fields in the `test.yml` file: `'MEAN_TARGET_COVERAGE', 'PCT_TARGET_BASES_20X', 'PCT_USABLE_BASES_ON_TARGET', 'TARGET_TERRITORY'`. Are the fields assigned to the `@header` array in [line 26](https://github.com/LMT337/qc_metrics.pl/blob/master/qc_metrics.pl#L26) supposed to be represented in all ---/--- blocks?

**Comment by LMT337** [comment]
New test file uploaded to master

**Comment by LMT337** [comment]
added complete file to master
